export const landingTheme = {
  accentText: "text-blue-600",
  accentTextStrong: "text-blue-700",
  accentTextHover: "hover:text-blue-700",
  accentBg: "bg-blue-600",
  accentBgHover: "hover:bg-blue-700",
  accentSoft: "bg-blue-50 text-blue-700",
  accentBorder: "border-blue-500",
  accentRing: "ring-blue-500/20",
  buttonPrimary: "bg-blue-600 text-white hover:bg-blue-700",
  buttonSecondary: "border border-slate-300 text-slate-900 hover:bg-slate-100",
  input:
    "bg-white border-slate-300 text-slate-900 placeholder:text-slate-400 focus:border-blue-500 focus:ring-blue-500",
  surface: "bg-white text-slate-900",
  surfaceMuted: "bg-slate-100",
  surfaceSubtle: "bg-slate-50",
  card: "bg-white border border-slate-200 shadow-sm",
  cardHover: "hover:border-slate-300 hover:shadow-md",
  textPrimary: "text-slate-900",
  textSecondary: "text-slate-600",
  textMuted: "text-slate-500",
  border: "border-slate-200",
  borderStrong: "border-slate-300",
  errorText: "text-red-600",
  errorBox: "bg-red-50 border border-red-200 text-red-700",
  successText: "text-emerald-600",
  focusRing: "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/40",
};
